drop table if exists pedidos_delivery;
drop table if exists reservas;
drop table if exists clientes;

create table clientes (
  id bigint generated by default as identity primary key,
  nome text not null,
  email text,
  telefone text not null,
  endereco text,
  criado_em timestamp with time zone default now()
);

create table reservas (
  id bigint generated by default as identity primary key,
  cliente_id bigint not null references clientes(id) on delete cascade,
  data_reserva date not null,
  horario time not null,
  quantidade_pessoas int not null,
  observacoes text,
  criado_em timestamp with time zone default now()
);

create table pedidos_delivery (
  id bigint generated by default as identity primary key,
  cliente_id bigint not null references clientes(id) on delete cascade,
  prato text not null,
  quantidade int not null,
  pagamento text not null,
  observacoes text,
  criado_em timestamp with time zone default now()
);

alter table clientes enable row level security;
alter table reservas enable row level security;
alter table pedidos_delivery enable row level security;

create policy "Permitir inserir clientes"
on clientes
for insert
to anon
with check (true);

create policy "Permitir ler clientes"
on clientes
for select
to anon
using (true);

create policy "Permitir inserir reservas"
on reservas
for insert
to anon
with check (true);

create policy "Permitir ler reservas"
on reservas
for select
to anon
using (true);

create policy "Permitir inserir pedidos delivery"
on pedidos_delivery
for insert
to anon
with check (true);

create policy "Permitir ler pedidos delivery"
on pedidos_delivery
for select
to anon
using (true);
